services:
  streamer:
    build: .
    ports:
      - "554:554"
    devices:
      - /dev/video0:/dev/video0
    environment:
      # SOURCE: "file"
      SOURCE: "webcam"
      CAMERA_DEVICE: "/dev/video0"
      VIDEO_PATH: "/videos/example_uav.mp4"
      RTSP_PORT: "554"
      MOUNT_POINT: "/main"
      WIDTH: "720"
      HEIGHT: "512"
      FRAMERATE: "25"
      BITRATE: "600"
    volumes:
      - ./videos:/videos:ro
